### ISSUE TITLE
Permission code doesnt work (or I'm just stupid) [ROCKET]

### ISSUE THREAD

**Issue by Crazys-Corner** [Dudewithoutname/DudeVoiceChat#1]
So the permission is dudevoice.change right? Well I added that to my Permissions config.xml and at first the test player couldn't talk in game at all, so I changed it to dudevoice.change.* and it started to do something, instead of constantly spamming chat with "you don't have the permission to use this voice level" or something it stopped doing that BUT said player could not be heard at all. When pressing comma, it would not change the voice level & instead say you don't have permission to.

Here's a copy of the default permissions section of permissionsconfig.xml:

      <Permissions>
        <Permission Cooldown="0">p</Permission>
        <Permission Cooldown="0">essentials.command.kits</Permission>
        <Permission Cooldown="0">essentials.command.kit</Permission>
        <Permission Cooldown="0">essentials.kit.starter</Permission>
        <Permission Cooldown="0">essentials.kit.paycheck</Permission>
        <Permission Cooldown="0">police.dragging</Permission>
        <Permission Cooldown="0">avi.admin.ess.maxskills</Permission>
        <Permission Cooldown="0">maxskills</Permission>
        <Permission Cooldown="0">essentials.command.warp</Permission>
        <Permission Cooldown="0">essentials.command.warps</Permission>
        <Permission Cooldown="0">essentials.warp.mines</Permission>
        <Permission Cooldown="0">essentials.warp.lumber</Permission>
        <Permission Cooldown="0">essentials.warp.spawn</Permission>
        <Permission Cooldown="0">discord</Permission>
        <Permission Cooldown="0">essentials.command.tpa.send</Permission>
        <Permission Cooldown="0">essentials.command.tpa.accept</Permission>
        <Permission Cooldown="0">essentials.command.tpa.deny</Permission>
        <Permission Cooldown="0">essentials.command.tpa.cancel</Permission>
        <Permission Cooldown="0">essentials.command.tpa</Permission>
        <Permission Cooldown="0">hs.addmember</Permission>
        <Permission Cooldown="0">craft.default</Permission>
        <Permission Cooldown="0">dudevoice.change.*</Permission>
        <Permission Cooldown="0">dudevoice.voice</Permission>
      </Permissions>

**Comment by Dudewithoutname** [comment]
Sorry i forgot to add a new release,i will add it after i come back home.

**Comment by Crazys-Corner** [comment]
Awesome, this is a great potential alternative to VoiceChat Master, just needs to work without Bluehammer.

**Comment by Dudewithoutname** [comment]
Should be fixed.
